backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "published"], default: "draft"}
